version: '3'
services:
  php:
    container_name: php
    build: './php/'
    volumes:
      - './public_html/:/var/www/html/'
    networks:
      - backend
  apache:
    container_name: apache
    build: './apache/'
    ports:
      - '8080:80'
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      - backend
      - frontend
    depends_on:
      - php
      - mysql
  mysql:
    container_name: mysql
    image: mysql:5.6.40
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - './data/:/var/lib/mysql'
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
networks:
  backend:
  frontend:
volumes:
    data:
